### ISSUE TITLE
Using Java 11 format language doesn't compatible to most of Fabric version Minecraft Launcher.

### ISSUE THREAD

**Issue by Void-heart** [nivoridocs/flowstone#4]
Crashing when uses Minecraft launcher to start Fabric version Minecraft, but **doesn't** in IntelliJ IDEA using Gradle built environment. The reason is you wrote this MOD under Java 11 environment. 
My Minecraft launcher's Fabric loader version: 0.11.1, Fabric version: 0.30.0+1.16(all newest). The same as IntelliJ's environment. So **IntelliJ** automatically uses mappings that are libraries from Java 11, but the vanilla launcher's **not.**

I checked just now that all Fabric MODs(nearly 30 from CurseForge) I'm using are under Java 8 environment. Except for this MOD...
p.s. take it easy. no need to hurry. I already fixed it before reporting this.

**Comment by nivoridocs** [comment]
I actually was a bit worried about that after all...
Well, thanks, a new fixed release will be available as soon as CurseForge approves my new file.

**Comment by Void-heart** [comment]
Oh my god... So quick... 😮

**Comment by Void-heart** [comment]
Can I pull req., or u determined to do it yrself bai yr IRON soul?(lol)

**Comment by nivoridocs** [comment]
Sure, but be aware that I might reject your pull request if I think it doesn't fit the project.
