### ISSUE TITLE
Mod is not server side

### ISSUE THREAD

**Issue by ExpertNugget** [NivOridocs/flowstone#7]

**Comment by NivOridocs** [comment]
Thank you for the heads up, but can you be more specific about the issue?

Do you need Flowstone to be server-side only? Are you facing a specific error in the logs? (If yes, can you share it here?) Are you just notifying me of an error in the Technical information on Modrinth?

I'll look into the issue regardless, but more context would be much appreciated.

**Comment by ExpertNugget** [comment]
On modrinth it's listed as server side

**Comment by NivOridocs** [comment]
Well, fixed, now on Modrinth is listed as a client-server mod.
